### ISSUE TITLE
URL decode password part

### ISSUE THREAD

**Issue by machow** [machow/dbpath#6]
Currently, dbpath does not URL decode parts like the password. This means that passwords with URL reserved characters (`@`, `:`, etc..) can't be represented.

See this SO on SQLALchemy using url encoding: https://stackoverflow.com/a/1424009/1144523

**Comment by gadenbuie** [comment]
If I'm reading the [linked source correctly](https://github.com/sqlalchemy/sqlalchemy/blob/main/lib/sqlalchemy/engine/url.py), it looks like we'd want to URL decode-encode the `password` and the query parameters. Anything else?
